### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by NyakoFox** [evolutionleo/LDtkParser#10]
I was thinking about using this in a project, and before I go ahead and do it, I'd like to know if this is still being maintained, since the last commit was in January.

**Comment by FaultyFunctions** [comment]
I believe if you run into any issues @evolutionleo will most likely be receptive to helping you out. I don't think there are any major changes to the json structure that would break with latest releases but I haven't personally tried 1.3.x. Maybe the multi-worlds feature introduced in 1.3.0 won't work correctly but that shouldn't be too much of an issue I don't think since it's still an experimental feature.

I personally have used this library on a decently large project as a base and have made changes to fit my project. It's very easy to change stuff around and customize if you run into an issues. I'd say try it out and open up an issue if you run into any problems or have questions. I can def try and help as well!

**Comment by NyakoFox** [comment]
Well, something else that worries me is that there's no release for the latest commits, either, which also seems to point towards this being fairly unmaintained...

**Comment by evolutionleo** [comment]
Yeah, sorry, I haven't worked on the parser for a while.

The project isn't really abandoned though, I do plan to come back to it sometime to update it, support all the new LDtk features that were introduced, etc.

I was initially paid to implement the parser, but now that that's not the case anymore I have much less motivation to work on it unfortunately, especially since I don't have any ongoing projects that rely on it currently either
